# Generated by Django 2.2.4 on 2020-04-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='gender',
            field=models.CharField(choices=[('man', 'Erkek'), ('woman', 'Kadın'), ('unisex', 'Unisex')], default='unisex', max_length=6),
        ),
    ]
