# Generated by Django 2.2.4 on 2020-04-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200421_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_home',
            field=models.BooleanField(default=False),
        ),
    ]
