# Generated by Django 2.2.4 on 2020-04-25 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20200425_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='session_key',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
